# Generated by Django 4.2.17 on 2024-12-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_3.servicebooking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_3.inventoryitem')),
            ],
        ),
    ]
