# Generated by Django 4.2.17 on 2024-12-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('service_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
